steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-east4-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/statement-parser:$COMMIT_SHA
      - -f
      - cloud-run/statement-parser/Dockerfile
      - cloud-run/statement-parser

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-east4-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/statement-parser:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - statement-parser
      - --image
      - us-east4-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/statement-parser:$COMMIT_SHA
      - --region
      - us-east4
      - --platform
      - managed

images:
  - us-east4-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/statement-parser:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY